name: ▶️ Start Clover Poller

on:
  workflow_dispatch:
  # Scheduled at 13:00 UTC → 09:00 EDT
  schedule:
    - cron: '0 13 * * *'

jobs:
  start:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN:       ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID:  ${{ secrets.RAILWAY_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link to Railway project
        run: railway link --project $RAILWAY_PROJECT_ID

      # Deploy in “detached” mode (no live logs) :contentReference[oaicite:1]{index=1}
      - name: Start service
        run: railway up --detach
